Enhance buckets
cisco/arc pull request #78
Opened 2018-02-08 22:18 UTC by danielcahoon

2018-02-09 03:24 UTC, icahoon requested changes

2018-02-09 03:24 UTC, icahoon commented on docs/design/storage/config.md
> +```json
Instead of ` ```json,` could you use just ` ``` `? Since it is currently marked as json code, and because ... isn't valid json, it is showing up as an error.

2018-02-09 03:24 UTC, icahoon commented on docs/design/storage/config.md
> +- **destination (string) _optional_: This is the target bucket for replication.
`**destination**` ?

2018-02-09 03:24 UTC, icahoon commented on docs/design/storage/config.md
> +_note_ role and destination are only used if the buckets are part of a bucket set.
Maybe `**NOTE**`

2018-02-09 03:24 UTC, icahoon commented on docs/design/storage/config.md
> +The storage feature introduces the "storage" section into the amp account configuration. The "storage" object is peer to the other top level json objects like provider and notifications.
At the end of the sentence, since "storage" is in quotes, perhaps "provider" and "notifications" should be too?

2018-02-09 03:24 UTC, icahoon commented on docs/design/storage/config.md
> +The "storage" section is a json object that contains two elements, the "buckets" element and the "buckets_sets" element. The "buckets" element is a json array of buckets. The "bucket_sets" element is
Maybe explain that a bucket_set differs from a bucket because it provides replication for all the buckets in the set?

2018-02-09 03:24 UTC, icahoon commented on docs/design/storage/config.md
> +- **role** (string) _optional_: This is the role used for cross region bucket replication.
Maybe comment that destination and role are required for bucket_sets?

2018-02-09 03:24 UTC, icahoon commented on docs/design/storage/config.md
> +Since the storage can have multiple bucket sets, the bucket_sets element
Looks like this needs to be completed.

2018-02-09 03:24 UTC, icahoon commented on docs/design/storage/config.md
> +  - **destination (string) _required_: This is the target bucket for replication.
`**destination**`

2018-02-09 03:24 UTC, icahoon commented on docs/design/storage/config.md
> +            "bucket": "sample-replicated-bucket-us-east-1"
needs a comma at the end of the line

2018-02-09 03:24 UTC, icahoon commented on docs/design/storage/config.md
> +            "bucket": "sample-replicated-bucket-us-east-2"
needs a comma at the end of the line

2018-02-09 03:24 UTC, icahoon commented on docs/design/storage/config.md
> +        ]
Missing a } after this line

2018-02-09 03:24 UTC, icahoon commented on docs/design/storage/config.md
> +
can remove the empty line

2018-02-09 03:24 UTC, icahoon commented on docs/design/storage/files
> +pkg/resource/account.go
Remove this line?

2018-02-09 03:24 UTC, icahoon commented on docs/design/storage/design.md
> +# Storage Services Design
Could you add a link in the top level README.md in the design section to this file?

2018-02-09 03:24 UTC, icahoon commented on pkg/amp/bucket_set.go
> +	buckets []resource.Bucket
This should probably be `buckets []*bucket`. I am changing the equivalent sections in the db code as well.

2018-02-09 03:24 UTC, icahoon commented on pkg/amp/amp.go
> +	if cfg.Storage == nil {
I think we should create an issue to make it so that storage can be an optional section in the amp config file. You can look at pkg/arc/arc.go as an example. And also look in the test/config directory. That test directory contains integrated tests and config files that verify that sections in arc can be optional.

2018-02-09 03:24 UTC, icahoon commented on pkg/config/storage.go
> +	if s.Buckets != nil {
You don't need to check Buckets against nil here, range is smart enough not to blow up if the slice is nil.

2018-02-09 03:24 UTC, icahoon commented on pkg/config/storage.go
> +	if s.BucketSets != nil {
As above.

2018-02-09 03:24 UTC, icahoon commented on pkg/config/amp.go
> +	if a.SecurityTags_ != nil {
Do you want to check the tags for nil?

2018-02-09 03:24 UTC, icahoon commented on pkg/resource/storage.go
> +
Should there be a `BucketSets() []BucketSet` method?

2018-02-09 03:24 UTC, icahoon commented on pkg/resource/bucket.go
> +	Informer
In general I prefer the order:

Loader
Creator
Destroyer
Provisioner
Auditor
Informer
Helper

And I am not saying that a DynamicBucket needs a Provisioner.

2018-02-09 03:24 UTC, icahoon commented on pkg/provider/storage.go
> +		log.Debug("%q | %+v", k, v)
Was this put in for debugging? Do you want to keep it in the code?

2018-02-09 03:24 UTC, icahoon commented on pkg/provider/storage.go
> +
Maybe remove this line

2018-02-09 03:24 UTC, icahoon commented on pkg/amp/bucket.go
> +func newBucket(cfg *config.Bucket, s *storage, prov provider.Storage) (resource.Bucket, error) {
I think it's better to return `(*bucket, error)` here

2018-02-09 03:24 UTC, icahoon commented on pkg/amp/bucket_set.go
> +	buckets []resource.Bucket
This should be []*bucket

2018-02-09 03:24 UTC, icahoon commented on pkg/amp/bucket_set.go
> +		msg.Error("Internal Error: Unknown command " + req.Command().String())
I don't think you need the error message here, it will be confusing. I think the help is sufficient.

2018-02-09 03:24 UTC, icahoon commented on pkg/amp/storage.go
> +	buckets         []resource.Bucket
This should be `[]*bucket`

2018-02-09 03:24 UTC, icahoon commented on pkg/amp/storage.go
> +	bucketSets      []resource.BucketSet
This should be `[]*bucketSet`

2018-02-09 03:24 UTC, icahoon commented on pkg/amp/storage.go
> +		b.Route(req)
You should be calling b.Info() here.

2018-02-09 03:24 UTC, icahoon commented on pkg/amp/storage.go
> +		bs.Route(req)
Should be calling b.Info() here

2018-02-09 03:24 UTC, icahoon commented on pkg/amp/storage.go
>  func (s *storage) info(req *route.Request) {
Shouldn't this be Info() ?

2018-02-13 16:26 UTC, gstragand approved these changes
lgtm

2018-02-13 19:30 UTC, icahoon approved these changes
thanks for making the changes

2018-02-13 19:45 UTC, merged

2018-02-13 19:46 UTC, danielcahoon commented
Closes Issue #69